#!/usr/bin/env bash
set -o pipefail
cd -- "$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)" || exit 1

while IFS= read -r -d '' dockerfile; do
  docker run --rm -v "$PWD:/work:ro" hadolint/hadolint:v2.12.0 \
    hadolint --config /work/hadolint.yaml "/work/${dockerfile#./}" || exit 1
done < <(find . -name Dockerfile -type f -print0)
